---
- name: Sleep for secondary nodes to come alive
  pause:
    minutes: 1
#  when: groups.mongod_primary.index(inventory_hostname) == 0 

- name: Ensure replicaset rs0 exists
  ignore_errors: yes
  community.mongodb.mongodb_replicaset:
    #login_host: localhost
    login_user: "{{mongodb_admin_user}}"
    login_password: "{{mongodb_admin_password}}"
    replica_set: rs0
    ssl_cert_reqs: "CERT_NONE"
    members:
    - kmaster.example.com:27017
    - kworker1.example.com:27017
    - kworker2.example.com:27017
#  when: groups.mongod_primary.index(inventory_hostname) == 0 

